# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1327, 481)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 45, 202, 35))
        self.pushButton.setObjectName("pushButton")
        self.pbSwitchMap = QtWidgets.QPushButton(self.centralWidget)
        self.pbSwitchMap.setGeometry(QtCore.QRect(10, 131, 101, 35))
        self.pbSwitchMap.setObjectName("pbSwitchMap")
        self.groupBoxShowGeneral = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBoxShowGeneral.setGeometry(QtCore.QRect(11, 169, 91, 125))
        self.groupBoxShowGeneral.setAutoFillBackground(True)
        self.groupBoxShowGeneral.setObjectName("groupBoxShowGeneral")
        self.cbShowMarkers = QtWidgets.QCheckBox(self.groupBoxShowGeneral)
        self.cbShowMarkers.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.cbShowMarkers.setObjectName("cbShowMarkers")
        self.cbShowConnections = QtWidgets.QCheckBox(self.groupBoxShowGeneral)
        self.cbShowConnections.setGeometry(QtCore.QRect(10, 40, 81, 17))
        self.cbShowConnections.setObjectName("cbShowConnections")
        self.cbShowInfo = QtWidgets.QCheckBox(self.groupBoxShowGeneral)
        self.cbShowInfo.setGeometry(QtCore.QRect(10, 60, 81, 17))
        self.cbShowInfo.setObjectName("cbShowInfo")
        self.pbToggleBounce = QtWidgets.QCheckBox(self.groupBoxShowGeneral)
        self.pbToggleBounce.setGeometry(QtCore.QRect(10, 100, 71, 21))
        self.pbToggleBounce.setObjectName("pbToggleBounce")
        self.pbToggleHeatmap = QtWidgets.QCheckBox(self.groupBoxShowGeneral)
        self.pbToggleHeatmap.setGeometry(QtCore.QRect(10, 80, 71, 21))
        self.pbToggleHeatmap.setObjectName("pbToggleHeatmap")
        self.groupBoxShowNodes = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBoxShowNodes.setGeometry(QtCore.QRect(110, 170, 101, 124))
        self.groupBoxShowNodes.setAutoFillBackground(True)
        self.groupBoxShowNodes.setObjectName("groupBoxShowNodes")
        self.cbShowGood = QtWidgets.QCheckBox(self.groupBoxShowNodes)
        self.cbShowGood.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.cbShowGood.setObjectName("cbShowGood")
        self.cbShowBad = QtWidgets.QCheckBox(self.groupBoxShowNodes)
        self.cbShowBad.setGeometry(QtCore.QRect(10, 60, 70, 17))
        self.cbShowBad.setObjectName("cbShowBad")
        self.cbShowPing = QtWidgets.QCheckBox(self.groupBoxShowNodes)
        self.cbShowPing.setGeometry(QtCore.QRect(10, 80, 71, 17))
        self.cbShowPing.setObjectName("cbShowPing")
        self.cbShowUnresolved = QtWidgets.QCheckBox(self.groupBoxShowNodes)
        self.cbShowUnresolved.setGeometry(QtCore.QRect(10, 40, 81, 17))
        self.cbShowUnresolved.setObjectName("cbShowUnresolved")
        self.cbShowKilled = QtWidgets.QCheckBox(self.groupBoxShowNodes)
        self.cbShowKilled.setGeometry(QtCore.QRect(10, 100, 71, 17))
        self.cbShowKilled.setObjectName("cbShowKilled")
        self.groupBoxStatusHosts = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBoxStatusHosts.setGeometry(QtCore.QRect(219, 40, 111, 38))
        self.groupBoxStatusHosts.setObjectName("groupBoxStatusHosts")
        self.labelHostsSolved = QtWidgets.QLabel(self.groupBoxStatusHosts)
        self.labelHostsSolved.setGeometry(QtCore.QRect(10, 15, 61, 16))
        self.labelHostsSolved.setObjectName("labelHostsSolved")
        self.statusHostsSolved = QtWidgets.QLabel(self.groupBoxStatusHosts)
        self.statusHostsSolved.setGeometry(QtCore.QRect(76, 13, 31, 20))
        self.statusHostsSolved.setObjectName("statusHostsSolved")
        self.groupBoxShowConnections = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBoxShowConnections.setGeometry(QtCore.QRect(11, 298, 91, 121))
        self.groupBoxShowConnections.setAutoFillBackground(True)
        self.groupBoxShowConnections.setObjectName("groupBoxShowConnections")
        self.cbShowGoodConn = QtWidgets.QCheckBox(self.groupBoxShowConnections)
        self.cbShowGoodConn.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.cbShowGoodConn.setObjectName("cbShowGoodConn")
        self.cbShowUnresolvedConn = QtWidgets.QCheckBox(self.groupBoxShowConnections)
        self.cbShowUnresolvedConn.setGeometry(QtCore.QRect(10, 40, 81, 17))
        self.cbShowUnresolvedConn.setObjectName("cbShowUnresolvedConn")
        self.cbShowBadConn = QtWidgets.QCheckBox(self.groupBoxShowConnections)
        self.cbShowBadConn.setGeometry(QtCore.QRect(10, 60, 70, 17))
        self.cbShowBadConn.setObjectName("cbShowBadConn")
        self.cbShowConnectionsActive = QtWidgets.QCheckBox(self.groupBoxShowConnections)
        self.cbShowConnectionsActive.setGeometry(QtCore.QRect(10, 80, 81, 17))
        self.cbShowConnectionsActive.setObjectName("cbShowConnectionsActive")
        self.cbShowKilledConn = QtWidgets.QCheckBox(self.groupBoxShowConnections)
        self.cbShowKilledConn.setGeometry(QtCore.QRect(10, 99, 81, 17))
        self.cbShowKilledConn.setObjectName("cbShowKilledConn")
        self.pbOpenFile = QtWidgets.QPushButton(self.centralWidget)
        self.pbOpenFile.setGeometry(QtCore.QRect(10, 88, 202, 35))
        self.pbOpenFile.setObjectName("pbOpenFile")
        self.groupBoxOptions = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBoxOptions.setGeometry(QtCore.QRect(110, 298, 101, 61))
        self.groupBoxOptions.setAutoFillBackground(True)
        self.groupBoxOptions.setObjectName("groupBoxOptions")
        self.cbPlot = QtWidgets.QCheckBox(self.groupBoxOptions)
        self.cbPlot.setGeometry(QtCore.QRect(10, 18, 70, 17))
        self.cbPlot.setChecked(False)
        self.cbPlot.setObjectName("cbPlot")
        self.cbSound = QtWidgets.QCheckBox(self.groupBoxOptions)
        self.cbSound.setGeometry(QtCore.QRect(10, 38, 70, 17))
        self.cbSound.setChecked(False)
        self.cbSound.setObjectName("cbSound")
        self.comboBoxInterface = QtWidgets.QComboBox(self.centralWidget)
        self.comboBoxInterface.setGeometry(QtCore.QRect(11, 7, 319, 31))
        self.comboBoxInterface.setObjectName("comboBoxInterface")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(220, 262, 111, 97))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("background-color: rgb(255, 247, 211);")
        self.groupBox.setObjectName("groupBox")
        self.cbKillBad = QtWidgets.QRadioButton(self.groupBox)
        self.cbKillBad.setGeometry(QtCore.QRect(10, 36, 70, 17))
        self.cbKillBad.setChecked(False)
        self.cbKillBad.setObjectName("cbKillBad")
        self.cbKillNone = QtWidgets.QRadioButton(self.groupBox)
        self.cbKillNone.setGeometry(QtCore.QRect(10, 17, 70, 17))
        self.cbKillNone.setChecked(True)
        self.cbKillNone.setObjectName("cbKillNone")
        self.cbKillAll = QtWidgets.QRadioButton(self.groupBox)
        self.cbKillAll.setGeometry(QtCore.QRect(10, 75, 70, 17))
        self.cbKillAll.setChecked(False)
        self.cbKillAll.setObjectName("cbKillAll")
        self.cbKillBandwidth = QtWidgets.QRadioButton(self.groupBox)
        self.cbKillBandwidth.setGeometry(QtCore.QRect(10, 56, 91, 17))
        self.cbKillBandwidth.setChecked(False)
        self.cbKillBandwidth.setObjectName("cbKillBandwidth")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(219, 137, 111, 55))
        self.groupBox_2.setObjectName("groupBox_2")
        self.statusNodes = QtWidgets.QLabel(self.groupBox_2)
        self.statusNodes.setGeometry(QtCore.QRect(75, 14, 31, 20))
        self.statusNodes.setObjectName("statusNodes")
        self.labelConnections_2 = QtWidgets.QLabel(self.groupBox_2)
        self.labelConnections_2.setGeometry(QtCore.QRect(9, 16, 61, 16))
        self.labelConnections_2.setObjectName("labelConnections_2")
        self.statusBadNodes = QtWidgets.QLabel(self.groupBox_2)
        self.statusBadNodes.setGeometry(QtCore.QRect(75, 31, 31, 20))
        self.statusBadNodes.setObjectName("statusBadNodes")
        self.labelBadNodes = QtWidgets.QLabel(self.groupBox_2)
        self.labelBadNodes.setGeometry(QtCore.QRect(9, 33, 61, 16))
        self.labelBadNodes.setObjectName("labelBadNodes")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(220, 194, 111, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.statusRxBytes = QtWidgets.QLabel(self.groupBox_3)
        self.statusRxBytes.setGeometry(QtCore.QRect(56, 34, 51, 20))
        self.statusRxBytes.setObjectName("statusRxBytes")
        self.labelRXBytes = QtWidgets.QLabel(self.groupBox_3)
        self.labelRXBytes.setGeometry(QtCore.QRect(10, 36, 41, 16))
        self.labelRXBytes.setObjectName("labelRXBytes")
        self.labelTXBytes = QtWidgets.QLabel(self.groupBox_3)
        self.labelTXBytes.setGeometry(QtCore.QRect(10, 15, 41, 16))
        self.labelTXBytes.setObjectName("labelTXBytes")
        self.statusTxBytes = QtWidgets.QLabel(self.groupBox_3)
        self.statusTxBytes.setGeometry(QtCore.QRect(56, 13, 51, 20))
        self.statusTxBytes.setObjectName("statusTxBytes")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setGeometry(QtCore.QRect(219, 80, 111, 55))
        self.groupBox_4.setObjectName("groupBox_4")
        self.statusConnections = QtWidgets.QLabel(self.groupBox_4)
        self.statusConnections.setGeometry(QtCore.QRect(75, 12, 31, 20))
        self.statusConnections.setObjectName("statusConnections")
        self.labelConnections = QtWidgets.QLabel(self.groupBox_4)
        self.labelConnections.setGeometry(QtCore.QRect(9, 14, 61, 16))
        self.labelConnections.setObjectName("labelConnections")
        self.labelKilledNodes = QtWidgets.QLabel(self.groupBox_4)
        self.labelKilledNodes.setGeometry(QtCore.QRect(10, 31, 60, 16))
        self.labelKilledNodes.setObjectName("labelKilledNodes")
        self.statusKilledNodes = QtWidgets.QLabel(self.groupBox_4)
        self.statusKilledNodes.setGeometry(QtCore.QRect(75, 31, 30, 20))
        self.statusKilledNodes.setObjectName("statusKilledNodes")
        self.listWidgetKilledProcesses = QtWidgets.QListWidget(self.centralWidget)
        self.listWidgetKilledProcesses.setGeometry(QtCore.QRect(338, 23, 131, 161))
        self.listWidgetKilledProcesses.setObjectName("listWidgetKilledProcesses")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(339, 3, 91, 16))
        self.label.setObjectName("label")
        self.listWidgetNodes = QtWidgets.QListWidget(self.centralWidget)
        self.listWidgetNodes.setGeometry(QtCore.QRect(477, 23, 531, 447))
        self.listWidgetNodes.setObjectName("listWidgetNodes")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(478, 4, 91, 16))
        self.label_2.setObjectName("label_2")
        self.pbGenerateReport = QtWidgets.QPushButton(self.centralWidget)
        self.pbGenerateReport.setGeometry(QtCore.QRect(530, 2, 161, 21))
        self.pbGenerateReport.setStyleSheet("background-color: rgb(225, 229, 255);")
        self.pbGenerateReport.setObjectName("pbGenerateReport")
        self.groupBoxPing = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBoxPing.setGeometry(QtCore.QRect(338, 298, 131, 121))
        self.groupBoxPing.setTitle("")
        self.groupBoxPing.setObjectName("groupBoxPing")
        self.cbPingIP = QtWidgets.QRadioButton(self.groupBoxPing)
        self.cbPingIP.setGeometry(QtCore.QRect(90, 43, 31, 17))
        self.cbPingIP.setChecked(True)
        self.cbPingIP.setObjectName("cbPingIP")
        self.cbPingAll = QtWidgets.QRadioButton(self.groupBoxPing)
        self.cbPingAll.setGeometry(QtCore.QRect(10, 43, 81, 17))
        self.cbPingAll.setChecked(False)
        self.cbPingAll.setObjectName("cbPingAll")
        self.pbPing = QtWidgets.QPushButton(self.groupBoxPing)
        self.pbPing.setGeometry(QtCore.QRect(9, 92, 113, 24))
        self.pbPing.setObjectName("pbPing")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBoxPing)
        self.groupBox_5.setGeometry(QtCore.QRect(0, -4, 131, 25))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.cbPingAuto = QtWidgets.QCheckBox(self.groupBox_5)
        self.cbPingAuto.setGeometry(QtCore.QRect(86, 5, 41, 17))
        self.cbPingAuto.setChecked(True)
        self.cbPingAuto.setObjectName("cbPingAuto")
        self.comboPing = QtWidgets.QComboBox(self.groupBoxPing)
        self.comboPing.setGeometry(QtCore.QRect(10, 65, 111, 22))
        self.comboPing.setObjectName("comboPing")
        self.cbPingRandom = QtWidgets.QRadioButton(self.groupBoxPing)
        self.cbPingRandom.setGeometry(QtCore.QRect(10, 25, 121, 17))
        self.cbPingRandom.setChecked(False)
        self.cbPingRandom.setObjectName("cbPingRandom")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(349, 298, 81, 16))
        self.label_3.setObjectName("label_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_6.setGeometry(QtCore.QRect(339, 189, 131, 101))
        self.groupBox_6.setStyleSheet("background-color: rgb(255, 247, 211);")
        self.groupBox_6.setObjectName("groupBox_6")
        self.comboKill = QtWidgets.QComboBox(self.groupBox_6)
        self.comboKill.setGeometry(QtCore.QRect(10, 43, 113, 22))
        self.comboKill.setObjectName("comboKill")
        self.pbKill = QtWidgets.QPushButton(self.groupBox_6)
        self.pbKill.setGeometry(QtCore.QRect(9, 72, 113, 24))
        self.pbKill.setObjectName("pbKill")
        self.cbKillAllNow = QtWidgets.QRadioButton(self.groupBox_6)
        self.cbKillAllNow.setGeometry(QtCore.QRect(10, 20, 41, 17))
        self.cbKillAllNow.setChecked(False)
        self.cbKillAllNow.setObjectName("cbKillAllNow")
        self.cbKillIP = QtWidgets.QRadioButton(self.groupBox_6)
        self.cbKillIP.setGeometry(QtCore.QRect(91, 20, 31, 17))
        self.cbKillIP.setChecked(True)
        self.cbKillIP.setObjectName("cbKillIP")
        self.cbKillBadNow = QtWidgets.QRadioButton(self.groupBox_6)
        self.cbKillBadNow.setGeometry(QtCore.QRect(50, 20, 41, 17))
        self.cbKillBadNow.setChecked(False)
        self.cbKillBadNow.setObjectName("cbKillBadNow")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_7.setGeometry(QtCore.QRect(110, 368, 221, 51))
        self.groupBox_7.setStyleSheet("background-color: rgb(255, 247, 211);")
        self.groupBox_7.setObjectName("groupBox_7")
        self.cbBlockBadInFirewall = QtWidgets.QCheckBox(self.groupBox_7)
        self.cbBlockBadInFirewall.setGeometry(QtCore.QRect(8, 19, 211, 17))
        self.cbBlockBadInFirewall.setChecked(False)
        self.cbBlockBadInFirewall.setObjectName("cbBlockBadInFirewall")
        self.ptSelectedIP = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.ptSelectedIP.setEnabled(True)
        self.ptSelectedIP.setGeometry(QtCore.QRect(1016, 23, 301, 447))
        self.ptSelectedIP.setToolTip("")
        self.ptSelectedIP.setObjectName("ptSelectedIP")
        self.cbAutoScrollNodes = QtWidgets.QCheckBox(self.centralWidget)
        self.cbAutoScrollNodes.setGeometry(QtCore.QRect(700, 3, 70, 17))
        self.cbAutoScrollNodes.setChecked(True)
        self.cbAutoScrollNodes.setObjectName("cbAutoScrollNodes")
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_8.setGeometry(QtCore.QRect(11, 420, 458, 51))
        self.groupBox_8.setObjectName("groupBox_8")
        self.comboShowHost = CheckableComboBox(self.centralWidget)
        self.comboShowHost.setGeometry(QtCore.QRect(20, 439, 439, 22))
        self.comboShowHost.setObjectName("comboShowHost")
        self.lblStatus = QtWidgets.QLabel(self.centralWidget)
        self.lblStatus.setGeometry(QtCore.QRect(1301, 1, 16, 20))
        self.lblStatus.setToolTip("")
        self.lblStatus.setToolTipDuration(-1)
        self.lblStatus.setStatusTip("")
        self.lblStatus.setStyleSheet("")
        self.lblStatus.setObjectName("lblStatus")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(1256, 2, 41, 16))
        self.label_4.setToolTip("")
        self.label_4.setToolTipDuration(5)
        self.label_4.setObjectName("label_4")
        self.statusHostsRequested = QtWidgets.QLabel(self.centralWidget)
        self.statusHostsRequested.setGeometry(QtCore.QRect(280, 500, 31, 20))
        self.statusHostsRequested.setObjectName("statusHostsRequested")
        self.labelHostsRequested = QtWidgets.QLabel(self.centralWidget)
        self.labelHostsRequested.setGeometry(QtCore.QRect(214, 502, 61, 16))
        self.labelHostsRequested.setObjectName("labelHostsRequested")
        self.statusHostsFailed = QtWidgets.QLabel(self.centralWidget)
        self.statusHostsFailed.setGeometry(QtCore.QRect(280, 530, 31, 20))
        self.statusHostsFailed.setObjectName("statusHostsFailed")
        self.labelHostsFailed = QtWidgets.QLabel(self.centralWidget)
        self.labelHostsFailed.setGeometry(QtCore.QRect(214, 532, 61, 16))
        self.labelHostsFailed.setObjectName("labelHostsFailed")
        self.statusHostsFailedOld = QtWidgets.QLabel(self.centralWidget)
        self.statusHostsFailedOld.setGeometry(QtCore.QRect(280, 560, 31, 20))
        self.statusHostsFailedOld.setObjectName("statusHostsFailedOld")
        self.labelHostsFailedOld = QtWidgets.QLabel(self.centralWidget)
        self.labelHostsFailedOld.setGeometry(QtCore.QRect(214, 562, 61, 16))
        self.labelHostsFailedOld.setObjectName("labelHostsFailedOld")
        self.statusHostsResolvedOld = QtWidgets.QLabel(self.centralWidget)
        self.statusHostsResolvedOld.setGeometry(QtCore.QRect(280, 590, 31, 20))
        self.statusHostsResolvedOld.setObjectName("statusHostsResolvedOld")
        self.labelHostsResolvedOld = QtWidgets.QLabel(self.centralWidget)
        self.labelHostsResolvedOld.setGeometry(QtCore.QRect(214, 592, 61, 16))
        self.labelHostsResolvedOld.setObjectName("labelHostsResolvedOld")
        self.pbShowMap = QtWidgets.QPushButton(self.centralWidget)
        self.pbShowMap.setGeometry(QtCore.QRect(111, 131, 101, 35))
        self.pbShowMap.setStyleSheet("background-color: rgb(225, 229, 255);")
        self.pbShowMap.setObjectName("pbShowMap")
        self.pbStartIpNetInfo = QtWidgets.QPushButton(self.centralWidget)
        self.pbStartIpNetInfo.setGeometry(QtCore.QRect(1015, 2, 101, 21))
        self.pbStartIpNetInfo.setStyleSheet("background-color: rgb(225, 229, 255);")
        self.pbStartIpNetInfo.setObjectName("pbStartIpNetInfo")
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_9.setGeometry(QtCore.QRect(1120, 2, 101, 21))
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.rbAllIpInfos = QtWidgets.QRadioButton(self.groupBox_9)
        self.rbAllIpInfos.setGeometry(QtCore.QRect(5, 2, 31, 17))
        self.rbAllIpInfos.setChecked(True)
        self.rbAllIpInfos.setObjectName("rbAllIpInfos")
        self.rbSelectedIpInfos = QtWidgets.QRadioButton(self.groupBox_9)
        self.rbSelectedIpInfos.setGeometry(QtCore.QRect(39, 2, 61, 17))
        self.rbSelectedIpInfos.setObjectName("rbSelectedIpInfos")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IPRadar2"))
        self.pushButton.setText(_translate("MainWindow", "live capture"))
        self.pbSwitchMap.setText(_translate("MainWindow", "switch map"))
        self.groupBoxShowGeneral.setTitle(_translate("MainWindow", "Show general"))
        self.cbShowMarkers.setText(_translate("MainWindow", "nodes"))
        self.cbShowConnections.setText(_translate("MainWindow", "connections"))
        self.cbShowInfo.setText(_translate("MainWindow", "info marker"))
        self.pbToggleBounce.setText(_translate("MainWindow", "bounce"))
        self.pbToggleHeatmap.setText(_translate("MainWindow", "heatmap"))
        self.groupBoxShowNodes.setTitle(_translate("MainWindow", "Show nodes"))
        self.cbShowGood.setText(_translate("MainWindow", "good"))
        self.cbShowBad.setText(_translate("MainWindow", "bad"))
        self.cbShowPing.setText(_translate("MainWindow", "ping neg."))
        self.cbShowUnresolved.setText(_translate("MainWindow", "unresolved"))
        self.cbShowKilled.setText(_translate("MainWindow", "killed"))
        self.groupBoxStatusHosts.setTitle(_translate("MainWindow", "Whos IP infos:"))
        self.labelHostsSolved.setText(_translate("MainWindow", "resolved:"))
        self.statusHostsSolved.setText(_translate("MainWindow", "0"))
        self.groupBoxShowConnections.setTitle(_translate("MainWindow", "Show conn.\'s"))
        self.cbShowGoodConn.setText(_translate("MainWindow", "good"))
        self.cbShowUnresolvedConn.setText(_translate("MainWindow", "unresolved"))
        self.cbShowBadConn.setText(_translate("MainWindow", "bad"))
        self.cbShowConnectionsActive.setText(_translate("MainWindow", "active conn."))
        self.cbShowKilledConn.setText(_translate("MainWindow", "killed"))
        self.pbOpenFile.setText(_translate("MainWindow", "open file"))
        self.groupBoxOptions.setTitle(_translate("MainWindow", "Options"))
        self.cbPlot.setText(_translate("MainWindow", "plot"))
        self.cbSound.setText(_translate("MainWindow", "sound"))
        self.groupBox.setTitle(_translate("MainWindow", "Kill conn.\'s (auto)"))
        self.cbKillBad.setText(_translate("MainWindow", "bad"))
        self.cbKillNone.setText(_translate("MainWindow", "none"))
        self.cbKillAll.setText(_translate("MainWindow", "all"))
        self.cbKillBandwidth.setText(_translate("MainWindow", "bandwidth limit"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Nodes"))
        self.statusNodes.setText(_translate("MainWindow", "0"))
        self.labelConnections_2.setText(_translate("MainWindow", "total:"))
        self.statusBadNodes.setText(_translate("MainWindow", "0"))
        self.labelBadNodes.setText(_translate("MainWindow", "bad:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Data"))
        self.statusRxBytes.setText(_translate("MainWindow", "0"))
        self.labelRXBytes.setText(_translate("MainWindow", "RX [KB]:"))
        self.labelTXBytes.setText(_translate("MainWindow", "TX [KB]:"))
        self.statusTxBytes.setText(_translate("MainWindow", "0"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Connections"))
        self.statusConnections.setText(_translate("MainWindow", "0"))
        self.labelConnections.setText(_translate("MainWindow", "current:"))
        self.labelKilledNodes.setText(_translate("MainWindow", "killed:"))
        self.statusKilledNodes.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Killed processes"))
        self.label_2.setText(_translate("MainWindow", "Nodes"))
        self.pbGenerateReport.setText(_translate("MainWindow", "create report_DATE.csv"))
        self.cbPingIP.setText(_translate("MainWindow", "IP:"))
        self.cbPingAll.setText(_translate("MainWindow", "all known"))
        self.pbPing.setText(_translate("MainWindow", "ping"))
        self.cbPingAuto.setText(_translate("MainWindow", "auto"))
        self.cbPingRandom.setText(_translate("MainWindow", "10 random IPs"))
        self.label_3.setText(_translate("MainWindow", "Ping Command"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Kill active conn.\'s Cmd"))
        self.pbKill.setText(_translate("MainWindow", "kill"))
        self.cbKillAllNow.setText(_translate("MainWindow", "all"))
        self.cbKillIP.setText(_translate("MainWindow", "IP:"))
        self.cbKillBadNow.setText(_translate("MainWindow", "bad"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Firewall (Windows)"))
        self.cbBlockBadInFirewall.setText(_translate("MainWindow", "add rule to block \"bad\" IPs automatically"))
        self.cbAutoScrollNodes.setText(_translate("MainWindow", "auto-scroll"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Show selected owners"))
        self.lblStatus.setText(_translate("MainWindow", "*"))
        self.label_4.setText(_translate("MainWindow", "status: "))
        self.statusHostsRequested.setText(_translate("MainWindow", "0"))
        self.labelHostsRequested.setText(_translate("MainWindow", "requested: "))
        self.statusHostsFailed.setText(_translate("MainWindow", "0"))
        self.labelHostsFailed.setText(_translate("MainWindow", "failed:"))
        self.statusHostsFailedOld.setText(_translate("MainWindow", "0"))
        self.labelHostsFailedOld.setText(_translate("MainWindow", "failed (past):"))
        self.statusHostsResolvedOld.setText(_translate("MainWindow", "0"))
        self.labelHostsResolvedOld.setText(_translate("MainWindow", "resol. (past):"))
        self.pbShowMap.setText(_translate("MainWindow", "show map"))
        self.pbStartIpNetInfo.setText(_translate("MainWindow", "ipnetinfo"))
        self.rbAllIpInfos.setText(_translate("MainWindow", "all"))
        self.rbSelectedIpInfos.setText(_translate("MainWindow", "selected"))
from CheckableComboBox import CheckableComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
